mentee/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views
from mentee.views import *


app_name = 'users'

urlpatterns = [
    path('login/callback', UserLoginView.as_view(), name='google_login'),
    path('dashboard',DashboardView.as_view(),name='dashboard_page'),
    # path('home', views.home, name='home_page'),
    path('', views.index, name='index'),
    # path('login-login/',views.play),
    path('add_mentor_details', views.insert_mentor_data, name='add_mentor_details'),
    path('register_profile', UserProfileView.as_view()),
    path('fetch_mentor_profile',FetchMentorProfile.as_view(),name='fetch_mentor_profile'),
    path('image/<int:id>/', MentorView.as_view(), name="mentor_view"),
    path('create_mentor_schedule', Mentor_Schedule_API.as_view(), name="mentor_schedule"),
    path('topic/', Mentor_Topics_API.as_view()),
    path('fetch_schedule', Fetch_Mentor_Schedule_Api.as_view()),
    path('calendar', Mentor_Calender_API.as_view()),
    path('deactivate', Row_Deactivate_API.as_view()),
    path('order', Booking_121.as_view()),
    path('profile/', Mentor_Profile_API.as_view()),
    path('mentor_booked_schedule', Booked_Sessions.as_view()),
    #path('excel/', excel_to_table.as_view()),
    path('create_order/', Create_Order_API.as_view()),
    path('verify_sign/', RP_Sign_Verification.as_view()),
    path('booked_schedule/', Booked_Sessions.as_view()),
    path('search', Search_API.as_view()),
    path('career_profile/', Fetch_Session_Names_API.as_view()),
    path('mentor_details/', Mentor_Details_API.as_view()),
    path('coupon/', Coupon_API.as_view()),
    path('mentee_orders/', Mentee_My_Orders_API.as_view()),
    path('mentor_orders/', Mentor_My_Orders_API.as_view()),
    path('pay_history/', Mentor_Payment_History.as_view()),
    path('mentee_feedback/', Mentee_Feedback.as_view()),
    path('get_call_token',VoiceCalling.as_view()),
    path('disconnect_call/',DisconnectCall.as_view()),
    path('wallet/', Wallet_API.as_view()),
    path('wallet_verify/', wallet_verification.as_view()),
    path('wallet_history/', wallet_history.as_view()),
    path('make_payment/', make_payment.as_view()),
    path('favourites/', update_favourite_mentors.as_view()),
    path('profile_page/', profile_page.as_view()),
    path('search_mentors/',FindMentors.as_view()),
    #path('rz_test/', Razorpay_test.as_view()),
    #path('pay_test/', Pay_test.as_view()),
    path('get_fav_mentors/', fetch_favourite_mentors.as_view()),
    path('request_session/', request_session.as_view()),  # 1
    path('mentor_notifications/', mentor_notifications.as_view()),
    path('notify_mentee/', notify_mentee.as_view()),  # 2
    path('mentee_notifications/', mentee_notifications.as_view()),
    path('channel_listener/', ChannelEventListener.as_view()),
    path('cancel_sess_req/', CancelSessionRequest.as_view()),

    path('mentor_form/<int:row_id>/', mentor_form, name="mentor_detail_form"),
    path('unregistered_mentors/', incomplete_mentor_profiles, name="unregistered_mentor_profiles"),
    path('submit_mentor_det/', submit_mentor_form, name="submit_mentor_details"),
    path('mentor_invalid/<int:row_id>/', mark_mentor_invalid, name="mark_mentor_invalid"),
    path('otp_verify/', otp_verify.as_view()),
    path('event_page/', event_page, name="event_page"),
    path('submit_event_info/', submit_event_info, name="submit_event_info"),
    path('fetch_event_info/', fetch_event_info.as_view(), name="fetch_event_info"),

    path('event_payment/', event_make_payment.as_view()),
    path('event_order/', event_order_api.as_view()),
    path('event_sign_verify/', event_sign_verify.as_view()),

 
    path('phone_check/', phone_num_check.as_view()),

    path('fill_account_details',AccountDetails.as_view()),

    path('mentee_profile/', mentee_profile.as_view()),

    path('profile_pic/', profile_pic.as_view()),  # profile pic url
    path('payment_status/', payment_status.as_view()),

]

mentorbox/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mentee/',include('mentee.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mentee/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User
 
class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email',)

mentee/views.py
import math, re
from .mentor import *
from mentee.agora.call import *
from django.db import connection
from rest_framework.views import APIView
from rest_framework.decorators import api_view
from rest_framework.generics import RetrieveAPIView
from django.views.generic.detail import DetailView

from django.http.response import Http404, HttpResponse
from .forms import SignUpForm
from django.views.decorators.csrf import csrf_exempt
import json
from django.core.exceptions import ObjectDoesNotExist
from .models import User
import datetime
from django.shortcuts import render
import uuid
# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from google.oauth2 import id_token
from dateutil.relativedelta import relativedelta
import io
from PIL import Image
import urllib.request
import jwt, json

# from django.shortcuts import redirect, render , render_to_response         #server
from django.shortcuts import redirect, render  # local

import requests
from google.auth.transport import requests
from django.contrib.auth import login, authenticate
from rest_framework import status
from rest_framework.generics import CreateAPIView
from rest_framework.response import Response
from rest_framework.permissions import AllowAny

from mentee.serializers import UserRegistrationSerializer, UserLoginSerializer

from rest_framework.generics import RetrieveAPIView
from rest_framework_jwt.settings import api_settings
from django.contrib.auth.models import update_last_login
from rest_framework.permissions import IsAuthenticated
from rest_framework_jwt.authentication import JSONWebTokenAuthentication

from django.shortcuts import get_object_or_404

from .models import MentorImage, mentor_schedule, mentor_topics, sales_order, mentor_profile, MentorFlow
from .serializers import MentorImageSerializer, mentor_schedule_serializer, mentor_topics_serializer, \
    sales_order_serializer

from rest_framework import status

from mentee.elastic_db import ElasticDB
from firebase_admin import auth, credentials, initialize_app
import time

# from sqlalchemy import create_engine                    #local
# import sqlalchemy                                       #local
cred = credentials.Certificate("mentee/firebase/mentorbox-inida-firebase-adminsdk-mnxz4-e883fceca5.json")
initialize_app(cred)
import razorpay  # local

es_ob = ElasticDB()

JWT_PAYLOAD_HANDLER = api_settings.JWT_PAYLOAD_HANDLER
JWT_ENCODE_HANDLER = api_settings.JWT_ENCODE_HANDLER


def index(request):
    return render(request, 'login.html')


class UserLoginView(RetrieveAPIView):
    permission_classes = (AllowAny,)

    # serializer_class = UserLoginSerializer

    def post(self, request):
        print(request.data)
        gmail_token = request.data['g_token']
        mobile_token = request.data['m_token']

        print(gmail_token, "-----------------")
        idinfo = id_token.verify_oauth2_token(gmail_token, requests.Request(),
                                              '242017925852-adacce81ou3vqqaiu6bpv2bg53571s5r.apps.googleusercontent.com')
        # idinfo = id_token.verify_oauth2_token(gmail_token, requests.Request(),
        #                                     '824991669873-4uvhv8anug1h4hv2gjo2g0hiclrcvvbn.apps.googleusercontent.com')
        print(idinfo, "id info")
        message = 'User already registered'
        status_code = status.HTTP_200_OK
        user_in_db = None
        response = {
            'success': True,

        }
        mentors = []
        try:
            user_in_db = User.objects.get(email=idinfo['email'])
            print(user_in_db, "1")
            print(user_in_db.pk, "2")
            is_mentee = user_in_db.is_mentee
            is_mentor = user_in_db.is_mentor

            if not is_mentee and not is_mentor:
                message = "User registered  successfully"
                status_code = status.HTTP_201_CREATED
            elif is_mentee or is_mentor:
                pass

        except ObjectDoesNotExist:
            user_in_db = User.objects.create_user(idinfo['email'], idinfo['name'], idinfo["picture"])
            print(user_in_db, "3")
            print(user_in_db.pk, "4")

            message = "User registered  successfully"
            status_code = status.HTTP_201_CREATED

        # saving mobile token
        user_in_db.mobile_token = mobile_token
        user_in_db.save()

        payload = JWT_PAYLOAD_HANDLER(user_in_db)
        jwt_token = JWT_ENCODE_HANDLER(payload)
        update_last_login(None, user_in_db)
        # jwt_token = jwt.encode(payload, "SECRET_KEY").decode('utf-8')
        response["message"] = message
        response["status_code"] = status_code
        response['token'] = jwt_token

        print(response, "response")
        return HttpResponse(json.dumps(response), status=status_code)


class DashboardView(RetrieveAPIView):
    # permission_classes = (IsAuthenticated,)
    # authentication_class = JSONWebTokenAuthentication

    permission_classes = (AllowAny,)

    def get(self, request):

        user_in_db = User.objects.get(email=request.user)
        # user_in_db = User.objects.get(email='neerajdtu2015@gmail.com')
        print(user_in_db.id, "user det", user_in_db.email)
        is_mentee = user_in_db.is_mentee
        is_mentor = user_in_db.is_mentor

        response = {
            'success': True,
            "status_code": 200,
            "is_mentee": True

        }

        message = 'User already registered'
        status_code = status.HTTP_200_OK

        if is_mentee:

            user_detail = MenteeDetails.objects.get(user_id=user_in_db.pk)
            # print(user_detail.career_list, "user_details", type(user_detail.career_list))
            if user_detail.profile == "student":

                user_detail_dict = {
                    # "College": user_detail.college,
                    #                 "Course": user_detail.course,
                    #                 "Degree": user_detail.degree,
                    "fields": json.loads(user_detail.career_list),
                    "Skills": json.loads(user_detail.skills)}
                mentors = es_ob.search_mentor_for_student(user_detail_dict)
            else:
                user_detail_dict = {
                    # "College": user_detail.college,
                    #                 "Degree": user_detail.degree,
                    "fields": json.loads(user_detail.career_list),
                    "Skills": json.loads(user_detail.skills),
                    "CurrentDesignation": user_detail.designation,
                    # "CurrentCompany": user_detail.company
                }
                mentors = es_ob.search_mentors_for_prof(user_detail_dict)

            so_rows = sales_order.objects.filter(Mentee_id=user_in_db.pk, Is_active=1, Status=1)

            upcoming_sessions = []
            for row in so_rows:
                schedule_id = row.Schedule_id
                mentor_id = row.Mentor_id
                men_prof = mentor_profile.objects.get(user_id=row.Mentor_id)
                avatar = men_prof.avatar
                name = men_prof.name
                industry_exp = men_prof.industry_exp
                position = json.loads(men_prof.professional_details)[0]['position']
                session_name = row.Session_name
                schedule_tab = mentor_schedule.objects.get(id=schedule_id)
                start_time = schedule_tab.Start_datetime

                diff_time = datetime.datetime.now() - start_time
                minutes_diff = diff_time.total_seconds() / 60
                print(minutes_diff, start_time, diff_time, "---------------------")
                if minutes_diff >= 60:
                    print("skipped some older sessions", start_time)
                    continue
                upcoming_sessions.append(
                    {"schedule_id": schedule_id, "id_": mentor_id, "name": name, "industry_exp": industry_exp,
                     "avatar": avatar,
                     "position": position, "session_at": start_time.strftime("%d %b, %I:%M %p"),
                     "session_name": session_name, "sort_key": str(start_time)})

            upcoming_sessions.sort(key=lambda x: x['sort_key'], reverse=False)

            response["data"] = {'recommended_mentors': mentors, "upcoming_sessions": upcoming_sessions,
                                "profile_verified": True}
            # print(user_in_db.pk,user_in_db.id,"-------------------------")
            req_sessions = mentee_notifications_func(user_in_db.id)
            print(req_sessions, "req_sessions")
            response["data"].update({"requested_sessions": req_sessions})
            # print(user_detail_dict)

        elif is_mentor:
            mentor_dict = {"mentor_id": user_in_db.pk, "is_scheduled": 1}
            upcoming_sessions = fetch_booked_sessions(mentor_dict)
            response["is_mentee"] = False
            response["data"] = {"upcoming_sessions": upcoming_sessions}
            message = "success"
            request_sessions = mentor_notifications_func(user_in_db.id)
            response["data"].update({"requested_sessions": request_sessions})

            response["data"].update({"profile_verified": MentorFlow.objects.get(user=user_in_db).details_filled})
        else:
            status_code = status.HTTP_201_CREATED
            message = "User has to fill registraion info"
            response["user_email"] = user_in_db.email
            response["user_name"] = user_in_db.name
            response["user_profile_pic"] = user_in_db.picture

            return HttpResponse(json.dumps(response), status=status_code)

        response["user_email"] = user_in_db.email
        response["user_name"] = user_in_db.name
        response["user_profile_pic"] = user_in_db.picture

        if not response["data"]['profile_verified']:
            response["data"].update({"message": "Profile verification is pending, We will notify you once it gets completed"})

mentee/templates/event_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link class="jsbin" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/base/jquery-ui.css" rel="stylesheet" type="text/css" />
    <script class="jsbin" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
    <script class="jsbin" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.0/jquery-ui.min.js"></script>
    <title>Webinar</title>

</head>
<body>


    <style>


            * {box-sizing: border-box;}

            body {
              margin: 0;
              font-family: Arial, Helvetica, sans-serif;
              background-color: whitesmoke;
            }

            .header {
              overflow: hidden;
              background-color: deepskyblue;
              padding: 20px 10px;
            }

            .header a {
              float: left;
              color: black;
              text-align: center;
              padding: 12px;
              text-decoration: none;
              font-size: 18px;
              line-height: 25px;
              border-radius: 4px;
            }

            .header a.logo {
              font-size: 25px;
              font-weight: bold;
            }





            .header-right {
              float: right;
            }

            @media screen and (max-width: 500px) {
              .header a {
                float: none;
                display: block;
                text-align: left;
              }

              .header-right {
                float: none;
              }
            }
        textarea{
            font-family: Arial, Helvetica, sans-serif;
        }

        table, th, td {
            border: 1px solid black;
          }

        table {
        width: 30%;
        }

        table {
            border-collapse: collapse;

          }



        th, td {
            padding: 15px;
            text-align: left;
          }




        tr:hover {background-color: #f2f2f2;}
        tr:nth-child(even) {background-color: #f2f2f2;}

        th {
            background-color: deepskyblue;
            text-align: center;
          }

        td{
            width: max-content;
        }

        .webinar_table{
            background-color: white;
            width: 60%;
            border-radius: 30px;
        }




        .alert {
            padding: 20px;
            background-color: #f44336;
            color: white;
            width: 90%;
          }
        .alert.success {background-color: #4CAF50;}

          .closebtn {
            margin-left: 15px;
            color: white;
            font-weight: bold;
            float: right;
            font-size: 22px;
            line-height: 20px;
            cursor: pointer;
            transition: 0.3s;
          }

          .closebtn:hover {
            color: black;
          }

    </style>

    <div class="header">
        <a href="{% url 'users:event_page' %}" class="logo">MentorBox</a>


      </div>
      <br>

    <div style="overflow-x:auto;">
    <center>


        {% if show %}

            {% if msg %}

            <div class="alert success">
                <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                <strong>Note:</strong> Saved Successfully
            </div>

            {% endif %}

            {% if not msg %}

            <div class="alert">
                <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                <strong>Note:</strong>Not saved!!! Please go back and check once again.
            </div>


            {% endif %}

        {% endif %}

    <form action="{% url 'users:submit_event_info' %}" method="POST" enctype="multipart/form-data">

    {% csrf_token %}

    <div class="webinar_table">

        <br>
        <h1>Webinar Details</h1>
    <table>
        <tr>
            <th>Fields</th>
            <th>Info</th>
        </tr>

        <tr>
            <td>
                <label for="web_title">Title<font color="red">*</font></label>
            </td>
            <td>
                <textarea name="title" id="web_title" oninvalid="alert('You must fill Title field!');" cols="100" rows="2"></textarea>
            </td>
        </tr>

        <tr>
            <td>
                <label for="web_image">Image<font color="red">*</font></label>
            </td>
            <td>
                <input type="file" name="image" id="web_image" onchange="img_display(this);">

            </td>
        </tr>


        <tr>
            <td>
                <label for="image_view">Uploaded Image</label>
            </td>
            <td>
                <img id="image_view" src="#" alt="view your image here"/>
            </td>

        </tr>

        <tr>
            <td>
                <label for="mentor_name">Mentor name<font color="red">*</font></label>
            </td>
            <td>
                <input type="text" name="mentor_name" id="mentor_name" placeholder="">
            </td>
        </tr>

        <tr>
            <td>
                <label for="event_type">Event type<font color="red">*</font></label>
            </td>
            <td>
                <input type="text" name="event_type" id="event_type" placeholder="">
            </td>
        </tr>

        <tr>
            <td>
                <label for="start_datetime">Start date and time<font color="red">*</font></label>
            </td>
            <td>
                <input type="datetime-local" name="start_datetime" id="start_datetime">
            </td>
        </tr>

        <tr>
            <td>
                <label for="duration">Duration<font color="red">*</font></label>
            </td>
            <td>
                <input type="text" name="duration" id="duration" placeholder="30 minutes">
            </td>
        </tr>

        <tr>
            <td>
                <label for="web_price">Webinar price<font color="red">*</font></label>
            </td>
            <td>
                <input type="number" name="price" id="web_price" placeholder="500">
            </td>
        </tr>

        <tr>
            <td>
                <label for="mentor_about">About the mentor<font color="red">*</font></label>
            </td>
            <td>
                <textarea name="mentor_about" id="mentor_about" cols="100" rows="5"></textarea>
            </td>
        </tr>

        <tr>
            <td>
                <label for="webinar_about">About the webinar<font color="red">*</font></label>
            </td>
            <td>
                <textarea name="webinar_about" id="webinar_about" cols="100" rows="5"></textarea>
            </td>
        </tr>


        <tr>
            <td>
                <label for="key_takeaways">Key Takeaways<font color="red">*</font></label>
            </td>
            <td>
                <textarea name="key_takeaways" id="key_takeaways" cols="100" rows="5"></textarea>
            </td>
        </tr>


    </table>

    <br>

    <input type="submit" value="Submit" name="submit" id="submot_btn">


    </div>
    </form>
    </center>
    <br>

    </div>


    <script>
        function img_display(input) {
            console.log("entered");
            console.log(input);
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#image_view')
                        .attr('src', e.target.result)
                        .width(150)
                        .height(200);
                };

                reader.readAsDataURL(input.files[0]);
                console.log(reader);
            }
        }
    </script>
</body>
</html>

mentee/templates/login.html
<html>
<head>
<!--  <meta name="google-signin-client_id" content="191322235073-vgj1avkfgsgmke4gqmlaj0rqr77u3ha1.apps.googleusercontent.com">-->
  <meta name="google-signin-client_id" content="824991669873-4uvhv8anug1h4hv2gjo2g0hiclrcvvbn.apps.googleusercontent.com">
</head>
<body>
  <div id="my-signin2"></div>
  <script>
    function onSuccess(googleUser) {
      console.log('Logged in as: ' + googleUser.getBasicProfile().getName());
      var id_token = googleUser.getAuthResponse().id_token;
      var xhr = new XMLHttpRequest();
<!--      xhr.open('POST', 'http://ec2-65-1-116-219.ap-south-1.compute.amazonaws.com:8000/mentee/login/callback');-->
      xhr.open('POST', 'http://localhost:8000/mentee/login/callback');
      xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
      xhr.onload = function() {
        console.log('Signed in as: ' + xhr.responseText);
      };
      xhr.send('g_token=' + id_token+'&m_token=vduvus');
    }
    function onFailure(error) {
      console.log(error);
    }
    function renderButton() {
      gapi.signin2.render('my-signin2', {
        'scope': 'profile email',
        'width': 240,
        'height': 50,
        'longtitle': true,
        'theme': 'dark',
        'onsuccess': onSuccess,
        'onfailure': onFailure
      });
    }
  </script>
  <a href="" onclick="signOut();">Sign out</a>
<script>
  function signOut() {
    var auth2 = gapi.auth2.getAuthInstance();
    auth2.signOut().then(function () {
      console.log('User signed out.');
    });
  }
</script>

  <button id="rzp-button1">Pay</button>
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
var options = {
    "key": "rzp_test_A5QQVVWf0eMog1", // Enter the Key ID generated from the Dashboard
    "amount": "100000", // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise
    "currency": "INR",
    "name": "Acme Corp",
    "description": "Test Transaction",
    "image": "https://media-exp1.licdn.com/dms/image/C4E03AQGCtp_Myr3I5g/profile-displayphoto-shrink_100_100/0/1600597138364?e=1612396800&v=beta&t=CgLtslnKB3LknIKVtQxux8akqJU94elt8D-XkLrHB80",
    "order_id": "order_GChkK943YkeW2z", //This is a sample Order ID. Pass the `id` obtained in the response of Step 1
    "handler": function (response){
        alert(response.razorpay_payment_id);
        alert(response.razorpay_order_id);
        alert(response.razorpay_signature)
    },
    "prefill": {
        "name": "Gaurav Kumar",
        "email": "gaurav.kumar@example.com",
        "contact": "9999999999"
    },
    "notes": {
        "address": "Razorpay Corporate Office"
    },
    "theme": {
        "color": "#3399cc"
    }
};
var rzp1 = new Razorpay(options)
 rzp1.on('payment.success', function (response){
    console.log("lo mai aa gaya")
     alert(response.razorpay_payment_id);
       alert(response.razorpay_order_id);
         alert(response.razorpay_signature)
         });

rzp1.on('payment.failed', function (response){
        alert(response.error.code);
        alert(response.error.description);
        alert(response.error.source);
        alert(response.error.step);
        alert(response.error.reason);
        alert(response.error.metadata.order_id);
        alert(response.error.metadata.payment_id);
});
document.getElementById('rzp-button1').onclick = function(e){
    rzp1.open();
    e.preventDefault();
}
</script>

  <script src="https://apis.google.com/js/platform.js?onload=renderButton" async defer></script>
</body>
</html>

mentee/templates/payment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    

    <button id="rzp-button1">Pay</button>
    <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
    <script>
    var options = {
        "key": 'rzp_test_A5QQVVWf0eMog1', // Enter the Key ID generated from the Dashboard
        "amount": "50000", // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise
        "currency": "INR",
        "name": "Acme Corp",
        "description": "Test Transaction",
        "image": "https://example.com/your_logo",
        "order_id": "{{order_id}}", //This is a sample Order ID. Pass the `id` obtained in the response of Step 1
        "handler": function (response){
            alert(response.razorpay_payment_id);
            alert(response.razorpay_order_id);
            alert(response.razorpay_signature)
        },
        "prefill": {
            "name": "Gaurav Kumar",
            "email": "gaurav.kumar@example.com",
            "contact": "9999999999"
        },
        "notes": {
            "address": "Razorpay Corporate Office"
        },
        "theme": {
            "color": "#3399cc"
        }
    };
    var rzp1 = new Razorpay(options);
    rzp1.on('payment.failed', function (response){
            alert(response.error.code);
            alert(response.error.description);
            alert(response.error.source);
            alert(response.error.step);
            alert(response.error.reason);
            alert(response.error.metadata.order_id);
            alert(response.error.metadata.payment_id);
    });
    document.getElementById('rzp-button1').onclick = function(e){
        rzp1.open();
        e.preventDefault();
    }
    </script>



</body>
</html>

mentee/templates/profile.html
<h1>My profile</h1>
<p>
  HEY WELCOME {{user}}
</p>
<a href="{% url 'mentee:logout' %}">Logout</a>

mentee/templates/signup.html
<h1>Sign up</h1>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Sign up</button>
</form>

mentee/templates/unregistered_mentors.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MentorBox</title>
</head>
<body>


    <style>

        table, th, td {
            border: 1px solid black;
          }

        table {
        width: 100%;
        }

        table {
            border-collapse: collapse;
          }


    </style>


    <table class="urls">
        <tr>
            <th>Linked Urls</th>
            <th>Fill Details</th>
            <th>Mark Invalid</th>
        </tr>
    {%  for obj in obj %}


        <tr>

            <td>{{obj.linkedin_url}}</td>
            <td><a href="{% url 'users:mentor_detail_form' obj.id %}"><input type="button" value="Fill">
            </a></td>
            <td><a href="{% url 'users:mark_mentor_invalid' obj.id %}"><input type="button" value="Invalid">
            </a></td>

        </tr>

    {% endfor %}

    </table>


</body>



</html>